@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package  UI <<Rectangle>>{
    class CommandHistory
    class CommandBox
}

CommandBox -right-> "1"CommandHistory
@enduml
